gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  user_provider: app_user_provider
  ttl: 2592000
  token_parameter_name: refresh_token
  firewall: api
  user_identity_field: email
